#!/bin/bash
# $1 report url
# $2 LOCAL_IP
# $3 LOCAL_MAC
# $4 VPN_CLIENT_VERSION
# $# 4

if [ $# -ne 4 ]
then
	echo "Update para error!"
else
req_string=$(echo $1"?LOCAL_IP="$2"&LOCAL_MAC="$3"&VPN_CLIENT_VERSION="$4)
#echo $req_string
req_result=$(curl $req_string)
echo $req_result
fi
